spring:
  application:
    name: my-rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mariandanscoi?reWriteBatchedInserts=true
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true


management:
  healt:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'

springfox.documentation.swagger:
  v2.path: ${management.endpoints.web.base-path}/swagger

---
pring.profiles.include: classicLogging

config:
  log-rest-template: true

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  config:
    activate:
      on-profile: local
