--liquibase formatted sql

--changeset t026dansm:ALE-4953-01
CREATE TABLE FILE_PAYMENTS
(
    ID                  SERIAL PRIMARY KEY,
    FROM_ACCOUNT        VARCHAR(20) NOT NULL,
    COMPANY_CIF         VARCHAR(10) NOT NULL,
    TOTAL_AMOUNT        REAL NOT NULL,
    ORIGINAL_FILE_NAME  VARCHAR(128) NOT NULL,
    FILE_NAME           VARCHAR(128) NOT NULL,
    PROCESSED           BOOLEAN DEFAULT FALSE NOT NULL,
    PROCESS_STATUS      INTEGER DEFAULT 0 NOT NULL,
    UPLOAD_CONFIRMED    BOOLEAN DEFAULT FALSE NOT NULL,
    FILE_CONTENT        BYTEA,
    INSERTED_AT         TIMESTAMP(6) NOT NULL,
    UPDATED_AT          TIMESTAMP(6) NOT NULL,
    INSERTED_BY         VARCHAR(50) NOT NULL,
    UPDATED_BY          VARCHAR(50) NOT NULL
);
--rollback;

--changeset t026dansm:ALE-4953-02
COMMENT ON TABLE FILE_PAYMENTS IS 'Table of file payments';

COMMENT ON COLUMN FILE_PAYMENTS.ID IS 'PK';
COMMENT ON COLUMN FILE_PAYMENTS.FROM_ACCOUNT IS 'Debit account from which payments are made';
COMMENT ON COLUMN FILE_PAYMENTS.COMPANY_CIF IS 'The company CIF';

COMMENT ON COLUMN FILE_PAYMENTS.TOTAL_AMOUNT IS 'Total amount of the debit transaction';
COMMENT ON COLUMN FILE_PAYMENTS.ORIGINAL_FILE_NAME IS 'User upload original filename';
COMMENT ON COLUMN FILE_PAYMENTS.FILE_NAME IS 'Formatted file name';
COMMENT ON COLUMN FILE_PAYMENTS.PROCESSED IS 'Flag to notify if transaction has been sent for processing';
COMMENT ON COLUMN FILE_PAYMENTS.UPLOAD_CONFIRMED IS 'Flag to notify if user has confirmed the uploaded file';
COMMENT ON COLUMN FILE_PAYMENTS.FILE_CONTENT IS 'Binary content of the file';
COMMENT ON COLUMN FILE_PAYMENTS.PROCESS_STATUS IS 'The status of the process';
COMMENT ON COLUMN FILE_PAYMENTS.UPDATED_BY IS 'updated by account';
COMMENT ON COLUMN FILE_PAYMENTS.UPDATED_AT IS 'updated at timestamp';
COMMENT ON COLUMN FILE_PAYMENTS.INSERTED_BY IS 'inserted by account';
COMMENT ON COLUMN FILE_PAYMENTS.INSERTED_AT IS 'inserted at timestamp';
--rollback ;

--changeset t026dansm:ALE-5709-01
ALTER TABLE FILE_PAYMENTS ADD FILE_HASH VARCHAR(128) DEFAULT '0' NOT NULL;
comment on column FILE_PAYMENTS.FILE_HASH
    is 'The hash of the uploaded file';

--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN FILE_HASH;

--changeset t026dansm:ALE-5709-02
ALTER TABLE FILE_PAYMENTS ADD PAYMENT_DESCRIPTION VARCHAR(128);
comment on column FILE_PAYMENTS.PAYMENT_DESCRIPTION
    is 'The description of the payment';

--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN PAYMENT_DESCRIPTION;

--changeset t026savai:ALE-5802
ALTER TABLE FILE_PAYMENTS ADD CURRENCY VARCHAR(3) DEFAULT 'RON' NOT NULL;
comment on column FILE_PAYMENTS.CURRENCY
    is 'The currency of the payment';

--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN CURRENCY;

--changeset t026dansm:ALE-6127-01
ALTER TABLE FILE_PAYMENTS DROP COLUMN PROCESSED;
ALTER TABLE FILE_PAYMENTS DROP COLUMN UPLOAD_CONFIRMED;
--rollback ;


--changeset t026dansm:ALE-6127-04
ALTER TABLE FILE_PAYMENTS ADD ERROR_MESSAGE VARCHAR;
comment on column FILE_PAYMENTS.ERROR_MESSAGE
    is 'The error message if any';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN ERROR_MESSAGE;

--changeset t026dansm:ALE-5709-03
ALTER TABLE FILE_PAYMENTS ADD FROM_ACCOUNT_KEY VARCHAR(30);
comment on column FILE_PAYMENTS.FROM_ACCOUNT_KEY
    is 'The account key of the payee account';

--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN FROM_ACCOUNT_KEY;

--changeset t026savai:ALE-7359-01
ALTER TABLE FILE_PAYMENTS ADD RESULT_FILE_CONTENT BYTEA;
comment on column FILE_PAYMENTS.RESULT_FILE_CONTENT
    is 'Binary content of the excel result file';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN RESULT_FILE_CONTENT;

--changeset t026savai:ALE-7359-02
ALTER TABLE FILE_PAYMENTS ADD SUCCESS_RESULT_FILE_NAME VARCHAR(128);
comment on column FILE_PAYMENTS.SUCCESS_RESULT_FILE_NAME
    is 'Name of the external MTA success result file.';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN SUCCESS_RESULT_FILE_NAME;

--changeset t026savai:ALE-7359-03
ALTER TABLE FILE_PAYMENTS ADD ERROR_RESULT_FILE_NAME VARCHAR(128);
comment on column FILE_PAYMENTS.ERROR_RESULT_FILE_NAME
    is 'Name of the external MTA error result file.';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN ERROR_RESULT_FILE_NAME;

--changeset t026savai:ALE-7359-04
ALTER TABLE FILE_PAYMENTS ADD RESULT_MESSAGE VARCHAR;
comment on column FILE_PAYMENTS.RESULT_MESSAGE
    is 'Message received from external MTA after processing the result.';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN RESULT_MESSAGE;


--changeset t026savai:ALE-7164
comment on column FILE_PAYMENTS.ERROR_MESSAGE
    is 'Failed file processing error message.';
--rollback;

--changeset t026savai:ALE-7479
ALTER TABLE FILE_PAYMENTS ADD PROCESSED_AMOUNT REAL DEFAULT 0 NOT NULL;
comment on column FILE_PAYMENTS.PROCESSED_AMOUNT
    is 'Processed amount from payment file.';
--rollback ALTER TABLE FILE_PAYMENTS DROP COLUMN PROCESSED_AMOUNT;

--changeset t026dansm:ALE-8077-01
ALTER TABLE FILE_PAYMENTS ADD CONSTRAINT CK_PROCESS_STATUS CHECK (PROCESS_STATUS>=0 AND PROCESS_STATUS<=6);
--rollback;